# Form implementation generated from reading ui file '.\GUICrawl.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 600)
        MainWindow.setStyleSheet("/* ===================================================\n"
"   1. NỀN CHUNG VÀ CÁC CHỮ (TEXT/LABEL)\n"
"   =================================================== */\n"
"QWidget#centralwidget {\n"
"    background-color: #f8f9fa; /* Màu nền xám trắng hiện đại */\n"
"}\n"
"\n"
"/* SỬA LỖI TÀNG HÌNH TIÊU ĐỀ CHÍNH */\n"
"QLabel#label {\n"
"    color: #2c3e50; /* Màu xám đen đậm cho chữ Tool Fuzzing */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Chữ \"Nhập URL\" */\n"
"QLabel#label_2 {\n"
"    color: #34495e; \n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    font-family: \"Segoe UI\", Roboto, Arial, sans-serif;\n"
"}\n"
"\n"
"/* ===================================================\n"
"   2. CÁC Ô NHẬP LIỆU VÀ HIỂN THỊ LOG (TEXT AREA)\n"
"   =================================================== */\n"
"QTextEdit, QTextBrowser {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #ced4da;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    color: #212529;\n"
"}\n"
"\n"
"/* Hiệu ứng khi bấm chuột vào ô nhập URL */\n"
"QTextEdit:focus {\n"
"    border: 2px solid #86b7fe; \n"
"}\n"
"\n"
"/* ===================================================\n"
"   3. BẢNG KẾT QUẢ VÀ CÁC TAB (TAB WIDGET)\n"
"   =================================================== */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 8px;\n"
"    background: #ffffff;\n"
"    top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #e9ecef;\n"
"    border: 1px solid #ced4da;\n"
"    padding: 8px 20px;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    margin-right: 2px;\n"
"    color: #495057;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    border-bottom-color: #ffffff;\n"
"    color: #0d6efd; /* Chữ màu xanh khi chọn tab */\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    border: none;\n"
"    gridline-color: #e9ecef;\n"
"    font-size: 13px;\n"
"    color: #212529;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #343a40; /* Nền đen nhạt cho tiêu đề bảng */\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #495057;\n"
"}\n"
"\n"
"/* ===================================================\n"
"   4. NÚT BẤM (BUTTON) - PHONG CÁCH PASTEL BO TRÒN\n"
"   =================================================== */\n"
"QPushButton {\n"
"    border-radius: 15px; /* Bo góc viên thuốc */\n"
"    font-family: \"Segoe UI\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"    border: 2px solid transparent;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #e9ecef;\n"
"    color: #adb5bd;\n"
"}\n"
"\n"
"/* ---> Nút Quét (Màu Xanh lam Pastel) <--- */\n"
"QPushButton#jBntScan { background-color: #cce5ff; color: #004085; }\n"
"QPushButton#jBntScan:hover { background-color: #b8daff; border: 2px solid #004085; }\n"
"\n"
"/* ---> Nút Path Traversal (Màu Cam Pastel) <--- */\n"
"QPushButton#pushButton { background-color: #fff3cd; color: #856404; }\n"
"QPushButton#pushButton:hover { background-color: #ffe8a1; border: 2px solid #856404; }\n"
"\n"
"/* ---> Nút SQLi (Màu Đỏ Pastel) <--- */\n"
"QPushButton#btnSQLi { background-color: #f8d7da; color: #721c24; }\n"
"QPushButton#btnSQLi:hover { background-color: #f5c6cb; border: 2px solid #721c24; }\n"
"\n"
"/* ---> Nút XSS (Màu Xanh lá Pastel) <--- */\n"
"QPushButton#btnXSS { background-color: #d4edda; color: #155724; }\n"
"QPushButton#btnXSS:hover { background-color: #c3e6cb; border: 2px solid #155724; }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtGetLink = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtGetLink.setGeometry(QtCore.QRect(80, 60, 221, 41))
        self.txtGetLink.setObjectName("txtGetLink")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 611, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #212529; /* Đổi màu chữ thành xám đậm/đen để nổi trên nền sáng */\n"
"    font-weight: bold;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setStyleSheet("font-family: \"Segoe UI\", Roboto, Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #34495e; /* Màu xám xanh đậm (Slate Gray) sang trọng */\n"
"    background-color: transparent; /* Nền trong suốt để không bị lộ viền vuông */\n"
"    padding-bottom: 2px;")
        self.label_2.setObjectName("label_2")
        self.jBntScan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.jBntScan.setGeometry(QtCore.QRect(310, 60, 121, 41))
        self.jBntScan.setStyleSheet("\n"
"\n"
"/* CSS */\n"
".button-33 {\n"
"  background-color: #c2fbd7;\n"
"  border-radius: 100px;\n"
"  box-shadow: rgba(44, 187, 99, .2) 0 -25px 18px -14px inset,rgba(44, 187, 99, .15) 0 1px 2px,rgba(44, 187, 99, .15) 0 2px 4px,rgba(44, 187, 99, .15) 0 4px 8px,rgba(44, 187, 99, .15) 0 8px 16px,rgba(44, 187, 99, .15) 0 16px 32px;\n"
"  color: green;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: CerebriSans-Regular,-apple-system,system-ui,Roboto,sans-serif;\n"
"  padding: 7px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: all 250ms;\n"
"  border: 0;\n"
"  font-size: 16px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
".button-33:hover {\n"
"  box-shadow: rgba(44,187,99,.35) 0 -25px 18px -14px inset,rgba(44,187,99,.25) 0 1px 2px,rgba(44,187,99,.25) 0 2px 4px,rgba(44,187,99,.25) 0 4px 8px,rgba(44,187,99,.25) 0 8px 16px,rgba(44,187,99,.25) 0 16px 32px;\n"
"  transform: scale(1.05) rotate(-1deg);\n"
"}")
        self.jBntScan.setObjectName("jBntScan")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 140, 921, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 911, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.Tab_2 = QtWidgets.QWidget()
        self.Tab_2.setObjectName("Tab_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.Tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 921, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.Tab_2, "")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 60, 191, 41))
        self.pushButton.setObjectName("pushButton")
        self.btnSQLi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSQLi.setGeometry(QtCore.QRect(630, 60, 131, 41))
        self.btnSQLi.setObjectName("btnSQLi")
        self.btnXSS = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXSS.setGeometry(QtCore.QRect(770, 60, 131, 41))
        self.btnXSS.setObjectName("btnXSS")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TOOL FUZZING KIỂM THỬ CƠ BẢN"))
        self.label_2.setText(_translate("MainWindow", "Nhập URL"))
        self.jBntScan.setText(_translate("MainWindow", "Bắt đầu quét"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "URL"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PAYLOAD"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TRẠNG THÁI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_2), _translate("MainWindow", "Kết quả "))
        self.pushButton.setText(_translate("MainWindow", "Tấn công path traversal"))
        self.btnSQLi.setText(_translate("MainWindow", "Tấn công SQLi"))
        self.btnXSS.setText(_translate("MainWindow", "Tấn công XSS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
